name: open_neom_lite
description: "A minimal Flutter application to showcase Open Neom Architecture & Generator."
version: 1.0.0-dev
homepage: https://github.com/Open-Neom/neom_app_lite

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  neom_core: ^1.4.1-dev
  neom_commons: ^1.4.1-dev
  neom_frequencies: ^1.3.0-dev
  neom_generator: ^1.3.0-dev
  neom_home: ^1.4.0-dev

  get: ^5.0.0-release-candidate-9.3.2
  logger: ^2.6.1
  intl: ^0.20.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
